### ISSUE TITLE
Issue in result format.

### ISSUE THREAD

**Issue by harshalyeole-tudip** [jgallen23/combinations#5]
I am using this package but I want the result in the array of strings instead of the array of arrays.

Ex.

INPUT: ['a', 'b', 'c']
CURRENT OUTPUT:
[ [ 'a' ],
  [ 'b' ],
  [ 'c' ],
  [ 'a', 'b' ],
  [ 'a', 'c' ],
  [ 'b', 'c' ],
  [ 'a', 'b', 'c' ] ]

EXPECTED OUTPUT:
[''a', 'b', 'c', 'a b', 'a c', 'a b c']

Please let know what I would need to change to get expected output.

**Comment by jgallen23** [comment]
could do that with map and join with the result
