### ISSUE TITLE
Master not released to npmjs

### ISSUE THREAD

**Issue by arve0** [jgallen23/combinations#8]
Hi!
Latest release (`v0.1.1`) seem to be a bit outdated, not supporting `maximum`.

**Comment by GCastilho** [comment]
@jgallen23 Any plans on releasing the update to npm?

**Comment by jgallen23** [comment]
latest should be on npm - is it not?

**Comment by GCastilho** [comment]
Info on readme says it supports max size, but info on npm does not says anything about a max size

I thought it was not updated, but I've tested here and both versions ignore the 'max' property

So, a bug?

**Comment by jgallen23** [comment]
maybe a bug - can you create a PR to fix?

**Comment by GCastilho** [comment]
no problem
